INSERT INTO C##KALUGER.BD6_DEPARTMENTS (ID, NAME, POSTAL_CODE, STREET, BUILDING, CITY) VALUES (10, 'Administration', '109658', 'Leningradskoe shosse', '1', 'Moscow');
INSERT INTO C##KALUGER.BD6_DEPARTMENTS (ID, NAME, POSTAL_CODE, STREET, BUILDING, CITY) VALUES (20, 'Marketing', '107701', 'Lenina', '22a', 'Volgograd');
INSERT INTO C##KALUGER.BD6_DEPARTMENTS (ID, NAME, POSTAL_CODE, STREET, BUILDING, CITY) VALUES (30, 'Purchasing', '109901', 'Mikluho-Maklaya', '8', 'Bryansk');
INSERT INTO C##KALUGER.BD6_DEPARTMENTS (ID, NAME, POSTAL_CODE, STREET, BUILDING, CITY) VALUES (40, 'Human Resources', '10967', '5-ya parkovaya', '16', 'Moscow');
INSERT INTO C##KALUGER.BD6_DEPARTMENTS (ID, NAME, POSTAL_CODE, STREET, BUILDING, CITY) VALUES (50, 'Shipping', '109659', '38 Bakinskih komissarov', '77', 'Moscow');
INSERT INTO C##KALUGER.BD6_DEPARTMENTS (ID, NAME, POSTAL_CODE, STREET, BUILDING, CITY) VALUES (60, 'IT', '109902', 'Pervomajskaya', '33', 'Kirov');